import Head from 'next/head'
import NavBar from '../components/NavBar'
import Hero from '../components/Hero'
import Image from 'next/image'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Another Escape</title>
        {/* <meta name="description" content="Generated by create next app" /> */}
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <NavBar/>
        <Hero />
      </div>
    </div>
  )
}
